plugins {
    id 'maven-publish'
    id 'com.enonic.xp.app'
    id 'com.enonic.defaults' version '2.1.6'
}

dependencies {
    include xplibs.portal
    include xplibs.websocket
    include libs.lib.thymeleaf
    include libs.lib.util
}

repositories {
    mavenCentral()
    xp.enonicRepo( 'dev' )
}
